### ISSUE TITLE
Fetch back all posts on up/down votes 

### ISSUE THREAD

**Issue by jewells07** [divanov11/Mumble#314]
Clicking on up/down votes, it is **fetching back all posts again** and if we vote post at downside it is **scrolling up**.

![bug](https://user-images.githubusercontent.com/54440548/116180871-43f37280-a737-11eb-8aa8-ed1b7950a018.jpeg)

**Comment by codyseibert** [comment]
I think the reducers should be modified to just increment / decrement the vote count on the mumble which the upvote / downvote was clicked on the UI instead of fetching back all the data.  Either that, or the upvote / downvote endpoint should return the single mumble data and we should replace that in state.
